[programs.devnet]
myepicproject = "37j9z8imWP4CBRGJRLbmkFWt68DstZdxG2mzAc71sES9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/leophamdev/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
